- name: Deploy a replica set via the kubernetes operator
  hosts: localhost
  roles:
    - role: mongodb_operator
      vars:
        mongodb_replicaset_backup: "{{ mongodb_replicaset_backup | bool }}"
