---

organization_id: "{{ operator_organization_details.resources[0].data.organization_id }}"
mongodb_organization_credentials_secret_name: "mongodb-{{ k8s_namespace }}-organization-credentials"
operator_project_details_configmap_name: "mongodb-{{ mongodb_replicaset_name }}-project-details"
k8s_cidr_ip_range: "40.89.244.188/24"
operator_organization_details_configmap_name : "mongodb-{{ k8s_namespace }}-organization-details"

mongodb_replicaset_name: "{{ k8s_namespace }}"
mongodb_replicaset_members: '3'
mongodb_replicaset_version: "4.2.2-ent"
mongodb_replicaset_external: 'false'
mongodb_replicaset_memory:
  request: "500M"                                                                                 
  limit: "2G"
mongodb_replicaset_cpu:
  request: "0.5"
  limit: "2"
mongodb_replicaset_auth:
  enabled: 'true'
  mode: "SCRAM"
mongodb_replicaset_persistent:
  enabled: 'true'
  multiple:
    enabled: 'false'
    data: "16G"
    journal: "1G"
    logs: "3G"
  single:
    storage: "16G"
#######################################

mongodb_patch_members: "{{ operator_replicaset_details.resources[0].spec.members }}"
mongodb_patch_version: "{{ operator_replicaset_details.resources[0].spec.version }}"
