---

- name: Confgiure access for cluster-wide mongoDB operator
  k8s:
    host: "{{ k8s_api_url }}"
    state: present
    definition: "{{ lookup('template', 'operator_access.yaml.j2') }}"
    verify_ssl: no
    api_key: "{{ k8s_api_key }}"

- name: Create an Ops Manager organization if not yet created
  include_tasks: create_org.yml
  when: "organization_id is not defined or (organization_id | length) == 0"

- name: Create project details configuration
  k8s:
    host: "{{ k8s_api_url }}"
    state: present
    definition: "{{ lookup('template', 'project_details.yaml.j2') }}"
    verify_ssl: no
    api_key: "{{ k8s_api_key }}"

- name: Create the replica set
  k8s:
    host: "{{ k8s_api_url }}"
    state: present
    definition: "{{ lookup('template', 'replicaset_resource.yaml.j2') }}"
    verify_ssl: no
    api_key: "{{ k8s_api_key }}"
