---

- name: Get MongoDB resource definition
  k8s_info:
    host: "{{ k8s_api_url }}"
    api_version: v1
    kind: MongoDB
    name: "{{ mongodb_replicaset_name }}"
    namespace: "{{ k8s_namespace }}"
  register: operator_replicaset_details

- name: Update the replica set
  k8s:
    state: present
    definition: "{{ lookup('template', 'replicaset_resource.yaml.j2') }}"
