---

- name: Update the replica set
  k8s:
    host: "{{ k8s_api_url }}"
    state: present
    definition: "{{ lookup('template', 'replicaset_resource.yaml.j2') }}"
    verify_ssl: no
    api_key: "{{ k8s_api_key }}"
