apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: api-access
rules:
  - apiGroups:
      - ""
      - mongodb.com
      - rbac.authorization.k8s.io
    resources:
      - mongodb
      - serviceaccounts
      - roles
      - rolebindings
      - configmaps
      - secrets
    verbs:
      - get
      - patch
      - create
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: api-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-access
subjects:
- kind: ServiceAccount
  name: api-service-account
  namespace: default
